In [1]:
import numpy as np
import pandas as pd
import os
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.neighbors import KNeighborsClassifier

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import CategoricalNB

from sklearn.pipeline import make_pipeline
import tdm
import math
import string
from sklearn.metrics import confusion_matrix, accuracy_score ,ConfusionMatrixDisplay, f1_score

from sklearn import preprocessing
from sklearn.pipeline import Pipeline

import nltk
from nltk.tokenize import sent_tokenize , word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
import re

from sklearn.naive_bayes import GaussianNB, MultinomialNB
import numpy as np

Functions to lemmatise the text and to correct OCR mistakes

In [2]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')


def ptb_to_wordnet(PTT):

    if PTT.startswith('J'):
        ## Adjective
        return 'a'
    elif PTT.startswith('V'):
        ## Verb
        return 'v'
    elif PTT.startswith('N'):
        ## Noune
        return 'n'
    elif PTT.startswith('R'):
        ## Adverb
        return 'r'
    else:
        return ''



find_replace = pd.read_csv('find_replace.csv')

lemmatiser = WordNetLemmatizer()


def clean_text(text):
    text = str(text).lower().strip()
    text = re.sub( r'~' , 't' , text)
    text = re.sub( r'\'' , '' , text)
    text = re.sub( r'`' , '' , text)
    text = re.sub( r'\s+' , ' ' , text)
    text = re.sub( r'(\. )+' , '. ' , text)
    text = re.sub( r'-\s+' , '' , text)
    text = re.sub( r'\.\.' , '' , text)
    text = re.sub( r'tet\'ritorial' , 'territorial' , text)
    text = re.sub( r'\bwa3\b' , 'was' , text)
    text = re.sub( r'popu:" lation' , 'population' , text)
    text = re.sub( f'^rst' , 'first' , text )
    text = re.sub( f'9ov:ernment' , 'government' , text )
    text = re.sub( r'vio!at' , 'violat' , text)
    text = re.sub( r'\brilthts\b' , 'rights' , text)
    text = re.sub( r'\badantic\b' , 'atlantic' , text)
    text = re.sub( r'\bobbgatlons\b' , 'obligations' , text)
    text = re.sub( r'\bmination\b' , '' , text)
    text = re.sub( r'self-detert' , 'self-determination' , text)
    text = re.sub( r'orgamzatlon' , 'organization' , text)
    text = re.sub( r'pretident' , 'president' , text)
    text = re.sub( r'deh10cratic' , 'democratic' , text)
    text = re.sub( r'\bhau\b' , 'have' , text)
    text = re.sub( r'·' , ' ' , text  ) 
    text = re.sub( r'cha!\'ter' , 'chapter' , text)
    text = re.sub( r'(\')+' , '\'' , text)

    return text.strip()
    

def lemmatise(text):
    text = str(text).lower()

    #lemmatise the quote
    words = word_tokenize(text)
    pos = nltk.pos_tag(words)
    lemmatised = ''

    for i in range( 0 , len(words) ):

        posTag = ptb_to_wordnet( pos[i][1] )
        if re.search( r'\w+' , posTag , re.IGNORECASE ):
            lemma = lemmatiser.lemmatize( words[i] , posTag )
            if re.search( r'\w' , lemma ):
                lemmatised += ' '
            if lemma not in stop_words:
                lemmatised += lemma 
        else:
            lemma = lemmatiser.lemmatize( words[i] )
            if re.search( r'\w' , lemma ):
                lemmatised += ' '
            if lemma not in stop_words:
                lemmatised += lemma 
            
    return lemmatised.strip()


The directory named 'Quotations' contains all excel files with manual classifications of the quotations, taken from speeches delivered in between 1950 and 1979. 

The quotations are saved as `features` and the assigned codes are the `targets`. The quotations are lemmatised and cleaned using the methods defined above. 

In [3]:
features = []
targets = []

dir = 'Quotations'

files = []
rows = []

for file in os.listdir(dir):
    if (re.search(r'xlsx',file) and not(re.search( r'~',file))):
        path = os.path.join(dir,file)
        files.append(path)

for file in files:
    print(file)

    # Read excel
    df = pd.read_excel(file)

    # fragments
    for index,row in df.iterrows():
        quote = row['Quotation Content']
        quote = clean_text(quote)
        quote = lemmatise(quote)

        all_codes = row['Codes']
        lines = re.split( r'\n' , all_codes )
        code = ''
        country = '' 
        year = ''

        for line in lines:
            #print(line)
            if re.search( r'^s_' , line.strip() , re.IGNORECASE ):
                country = re.sub( r'^[Ss]_' , '' , line.upper() , re.IGNORECASE )
                
            if re.search( r'^y_' , line.strip() , re.IGNORECASE ):
                year = re.sub( r'^[Yy]_' , '' , line.upper() , re.IGNORECASE )
                
                if re.search( r'\(' , year): 
                    year = year[ :year.index('(') ].strip()
                year = int(year)

            
            if re.search( r'^m_' , line.strip()  ):
                code = line.lower()
                
        if code != 'm_specific multlilateral agreement' and code != 'm_quote' and len(code)>0 and quote != 'nan':

            ## inconsistent spellings
            if code == 'm_non intervention':
                code = 'm_non-intervention'

            elif code == 'm_non interference':
                code = 'm_non-interference'

            code = re.sub( r'[-]','_',code )
            code = re.sub( r'\s+' , '_' , code )

            features.append(quote)
            targets.append(code)

            rows.append( [file,country,year,quote,row['Quotation Content'],code] )


Quotations/List of quotations 1960-69.xlsx
Quotations/List of quotations 1955-59.xlsx
Quotations/List of quotations 1970-74.xlsx
Quotations/List of quotations 1975-79.xlsx
Quotations/List of quotations 1950-54.xlsx


The data from the Excel files is captured in a CSV file

In [4]:
columns = ['file_name', 'country', 'year', 'text', 'orig_text', 'category']
df_quotations = pd.DataFrame(rows,columns=columns)
df_quotations.to_csv('quotations_1950-1979.csv')

In [5]:
print( f'The excel files contain {df_quotations.shape[0]} quotations')

The excel files contain 4126 quotations


Create a training set and a test set, with a test set size of 30% 

In [6]:
for t in sorted(set(targets)):
    print(t)
    
# encoder = LabelEncoder()
# encoded_labels = encoder.fit(targets)
# labels_names = dict(zip(encoded_labels.classes_, encoded_labels.transform(encoded_labels.classes_)))
# targets = encoder.fit_transform(targets)

# print(targets)

m_cold_war
m_colonialism
m_general_reference_to_foreign_policy
m_historical_reference
m_non_interference
m_non_intervention
m_reference_to_state_leader
m_sovereignty_limited
m_specific_conflict
m_specific_multilateral_agreement
m_un_design
m_un_mandate
m_un_membership


Replace textual labels with numeric labels

In [7]:
features_train, features_test, targets_train , targets_test = train_test_split(
    features, targets, test_size=0.3, random_state=125
)

print(f'The training set contains {len(features_train)} quotations.')
print(f'The test set contains {len(features_test)} quotations.')

The training set contains 2888 quotations.
The test set contains 1238 quotations.


## K-nearest Neighbours

In [8]:
vec = TfidfVectorizer(binary=True, use_idf=True)

tfidf_train = vec.fit_transform(features_train).toarray()

knn = KNeighborsClassifier(n_neighbors=25)

knn_model = knn.fit( tfidf_train, targets_train )

# # Predict Output
predictions = knn_model.predict(tfidf_train)

print( confusion_matrix(targets_train, predictions  ) )
print( accuracy_score(targets_train, predictions) )

[[197   4  20   0   1   1   0  58  52   0   0   0   3]
 [ 18 102   5   0   0   0   0  61  89   0   0   2  11]
 [ 23   2  43   0   0   0   0  26  13   0   0   0   1]
 [  5   6   1   0   0   0   0  18  16   0   0   0   1]
 [ 25   1   6   0  14   0   0  50  47   0   0   0   1]
 [ 12   1   0   0   0   0   0  13  32   0   0   0   0]
 [  1   2   0   0   0   0  15   4   6   0   0   0   0]
 [ 26   7   9   0   2   0   0 485  68   0   0   1   1]
 [ 11  14  10   0   3   0   0  58 692   0   0   0   0]
 [ 17   2   3   0   1   0   0  35  25   5   0   0   2]
 [  3   0   2   0   0   0   0  32  11   0   2   1   4]
 [  4   8   2   0   2   0   0  70  66   0   0   4   5]
 [  9  13   2   0   0   0   1  28  29   0   0   1 103]]
0.5754847645429363


In [9]:

tfidf_test = vec.transform(features_test).toarray()

# Predict Output
predictions = knn_model.predict(tfidf_test)

print( confusion_matrix(targets_test , predictions  ) )
print( accuracy_score(targets_test ,predictions) )

[[ 70   4   7   0   1   0   0  22  39   0   0   0   2]
 [  4  39   1   0   1   0   0  31  48   0   0   0   6]
 [  8   3  18   0   1   0   0  18   9   0   0   0   3]
 [  4   2   0   0   0   0   0   8   6   0   0   0   0]
 [  9   1   3   0   2   0   0  16  12   0   0   0   0]
 [  5   1   0   0   2   0   0   7  13   0   0   0   0]
 [  0   0   0   0   0   0   7   2   4   0   0   0   0]
 [ 14   4   3   0   2   0   0 187  33   0   0   2   2]
 [ 11  11   3   0   1   0   0  20 271   0   0   0   0]
 [  9   0   1   0   1   0   0  13   7   0   0   0   0]
 [  1   0   0   0   0   0   0  27   5   0   0   1   2]
 [  4   3   3   0   0   0   0  36  35   0   0   1   2]
 [  3   7   2   0   0   0   0  17  17   0   0   0  38]]
0.5113085621970921


## Naive Bayes

Train a model based on Naive Bayes. 


In [10]:

vec = TfidfVectorizer(binary=True, use_idf=True)
tfidf_train = vec.fit_transform(features_train).toarray()


# Build a Gaussian Classifier
nb = GaussianNB()
nb_model = nb.fit(tfidf_train, targets_train )

# Predict Output
predictions = nb_model.predict(tfidf_train)

print( confusion_matrix(targets_train , predictions  ) )
print( accuracy_score(targets_train ,predictions) )

[[321   5   2   0   4   0   0   0   0   2   0   1   1]
 [  0 275   4   0   2   2   1   0   0   0   0   1   3]
 [  0   0 108   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  47   0   0   0   0   0   0   0   0   0]
 [  0   0   2   0 142   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  58   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  28   0   0   0   0   0   0]
 [  9  11   7   0  13   2   0 544   0   6   1   4   2]
 [  8  14   2   1  10   4   0  10 726   2   0   6   5]
 [  0   0   0   0   0   2   1   0   0  86   1   0   0]
 [  0   0   0   0   0   0   1   0   0   0  54   0   0]
 [  0   0   0   1   1   0   0   0   0   0   0 159   0]
 [  0   0   0   1   0   0   0   0   0   0   1   0 184]]
0.945983379501385


In [11]:
# testData = count_vectorizer.transform(testData)
# tfidf_test_data = tfidf_transformer.transform(testData)

x_test = vec.transform(features_test).toarray()

# Predict Output
predictions = nb_model.predict(x_test)

print( confusion_matrix(targets_test , predictions  ) )
print( accuracy_score(targets_test ,predictions) )

[[ 30   5   2   1   4   1   0  36  56   3   0   3   4]
 [  9  21   1   0   3   1   0  24  57   1   0   2  11]
 [  9   6  10   0   1   0   0  13  18   0   0   1   2]
 [  1   2   1   0   0   0   0   0  15   0   0   0   1]
 [  4   1   0   1   7   1   0  15  13   0   0   1   0]
 [  2   1   1   0   0   0   1   2  17   0   1   3   0]
 [  1   0   0   0   0   0   4   4   4   0   0   0   0]
 [ 18  11   4   1   5   1   0 119  67   4   1  12   4]
 [ 29  18   4   0   4   2   1  46 200   3   0   8   2]
 [  3   0   0   0   1   0   0  16  10   1   0   0   0]
 [  4   0   0   0   2   0   1  19   8   0   0   1   1]
 [ 13   2   0   0   3   0   0  27  31   2   0   4   2]
 [  1  11   0   0   1   0   1  12  35   0   0   3  20]]
0.3360258481421648


## Read in texts to be annotated from TXT folder

The folder named 'TXT' contains transcripts of speeches delivered during the period 1970-2020.  

The code below extracts the sentences containing the term 'sovereign'.

In [12]:
dir = 'TXT'

txt_files = []

for root,dirs,files in os.walk( dir ):
    for file_name in files:
        
        if re.search( r'txt$' , file_name , re.IGNORECASE ) and not( re.search( r'^\.' , file_name , re.IGNORECASE ) ):
            txt_files.append( os.path.join(root, file_name) )

quotations = []

column_names = ['file_name','country','year','text','orig_text']
#sentences containing the word 'sovereign saved in df_result'
df_result = pd.DataFrame( columns = column_names )

quote_index = 0 
            
for file_name in txt_files:
    print(file_name)

    base_name = os.path.basename( file_name )
    base_name = re.sub( r'\.txt$' , '' , base_name )
    parts = re.split( r'_' , base_name )
    country = parts[0].strip()
    

    year = parts[2].strip()
    if re.search( r'_' , year ):
        year = year[ year.index('_')+1:]
    year = int(year)
    
    if not isinstance(year, int):
        print("year is an integer")
    

    with open( file_name , encoding = 'utf-8' ) as fh:
        #print(file_name)
        row = []
        speech = fh.read()
        #speech = clean_text(speech)
        sentences = sent_tokenize(speech)

        for quote in sentences:
            orig_quote = quote
            
            quote = re.sub( r'\s+' , ' ' , quote )
            if re.search( r'sovereign' , quote , re.IGNORECASE ):
                hits = re.findall( r'sovereign' , quote , re.IGNORECASE )

                quote_index += 1
                quote = re.sub( r',' , '' , quote )  
                quote = clean_text(quote)
                quote = lemmatise(quote)
                file_name_base = file_name[ file_name.index('/')+1 :]
                df_result.loc[quote_index] = [file_name_base,country,year,quote,orig_quote]
   

TXT/Session 73 - 2018/BRB_73_2018.txt
TXT/Session 73 - 2018/IND_73_2018.txt
TXT/Session 73 - 2018/ARG_73_2018.txt
TXT/Session 73 - 2018/JOR_73_2018.txt
TXT/Session 73 - 2018/SWE_73_2018.txt
TXT/Session 73 - 2018/EST_73_2018.txt
TXT/Session 73 - 2018/MDG_73_2018.txt
TXT/Session 73 - 2018/BTN_73_2018.txt
TXT/Session 73 - 2018/NOR_73_2018.txt
TXT/Session 73 - 2018/TUN_73_2018.txt
TXT/Session 73 - 2018/NRU_73_2018.txt
TXT/Session 73 - 2018/SWZ_73_2018.txt
TXT/Session 73 - 2018/ALB_73_2018.txt
TXT/Session 73 - 2018/IDN_73_2018.txt
TXT/Session 73 - 2018/BOL_73_2018.txt
TXT/Session 73 - 2018/SRB_73_2018.txt
TXT/Session 73 - 2018/GNQ_73_2018.txt
TXT/Session 73 - 2018/SYR_73_2018.txt
TXT/Session 73 - 2018/RUS_73_2018.txt
TXT/Session 73 - 2018/DJI_73_2018.txt
TXT/Session 73 - 2018/GIN_73_2018.txt
TXT/Session 73 - 2018/BHS_73_2018.txt
TXT/Session 73 - 2018/DNK_73_2018.txt
TXT/Session 73 - 2018/MYS_73_2018.txt
TXT/Session 73 - 2018/BRN_73_2018.txt
TXT/Session 73 - 2018/BGD_73_2018.txt
TXT/Session 

TXT/Session 29 - 1974/HUN_29_1974.txt
TXT/Session 29 - 1974/ISL_29_1974.txt
TXT/Session 29 - 1974/YUG_29_1974.txt
TXT/Session 29 - 1974/GRC_29_1974.txt
TXT/Session 29 - 1974/VEN_29_1974.txt
TXT/Session 29 - 1974/COD_29_1974.txt
TXT/Session 29 - 1974/CYP_29_1974.txt
TXT/Session 29 - 1974/COG_29_1974.txt
TXT/Session 29 - 1974/AUT_29_1974.txt
TXT/Session 29 - 1974/MEX_29_1974.txt
TXT/Session 29 - 1974/MYS_29_1974.txt
TXT/Session 29 - 1974/BGD_29_1974.txt
TXT/Session 29 - 1974/DDR_29_1974.txt
TXT/Session 29 - 1974/CAF_29_1974.txt
TXT/Session 29 - 1974/BGR_29_1974.txt
TXT/Session 29 - 1974/GBR_29_1974.txt
TXT/Session 29 - 1974/CHN_29_1974.txt
TXT/Session 29 - 1974/BFA_29_1974.txt
TXT/Session 29 - 1974/PRT_29_1974.txt
TXT/Session 29 - 1974/CRI_29_1974.txt
TXT/Session 29 - 1974/ECU_29_1974.txt
TXT/Session 29 - 1974/DZA_29_1974.txt
TXT/Session 29 - 1974/PHL_29_1974.txt
TXT/Session 29 - 1974/LKA_29_1974.txt
TXT/Session 29 - 1974/POL_29_1974.txt
TXT/Session 29 - 1974/BTN_29_1974.txt
TXT/Session 

TXT/Session 50 - 1995/ITA_50_1995.txt
TXT/Session 50 - 1995/ARE_50_1995.txt
TXT/Session 50 - 1995/LVA_50_1995.txt
TXT/Session 50 - 1995/TCD_50_1995.txt
TXT/Session 50 - 1995/PNG_50_1995.txt
TXT/Session 50 - 1995/NIC_50_1995.txt
TXT/Session 50 - 1995/SVK_50_1995.txt
TXT/Session 50 - 1995/FJI_50_1995.txt
TXT/Session 50 - 1995/TZA_50_1995.txt
TXT/Session 50 - 1995/BIH_50_1995.txt
TXT/Session 50 - 1995/KWT_50_1995.txt
TXT/Session 50 - 1995/NAM_50_1995.txt
TXT/Session 50 - 1995/IRN_50_1995.txt
TXT/Session 50 - 1995/SEN_50_1995.txt
TXT/Session 50 - 1995/NGA_50_1995.txt
TXT/Session 50 - 1995/IRQ_50_1995.txt
TXT/Session 50 - 1995/MLT_50_1995.txt
TXT/Session 50 - 1995/YEM_50_1995.txt
TXT/Session 50 - 1995/JAM_50_1995.txt
TXT/Session 50 - 1995/PRY_50_1995.txt
TXT/Session 50 - 1995/THA_50_1995.txt
TXT/Session 50 - 1995/HRV_50_1995.txt
TXT/Session 50 - 1995/GAB_50_1995.txt
TXT/Session 50 - 1995/MCO_50_1995.txt
TXT/Session 50 - 1995/BHR_50_1995.txt
TXT/Session 50 - 1995/AND_50_1995.txt
TXT/Session 

TXT/Session 64 - 2009/TON_64_2009.txt
TXT/Session 64 - 2009/CHL_64_2009.txt
TXT/Session 64 - 2009/DEU_64_2009.txt
TXT/Session 64 - 2009/COL_64_2009.txt
TXT/Session 64 - 2009/TLS_64_2009.txt
TXT/Session 64 - 2009/PSE_64_2009.txt
TXT/Session 64 - 2009/PER_64_2009.txt
TXT/Session 64 - 2009/SYC_64_2009.txt
TXT/Session 64 - 2009/LTU_64_2009.txt
TXT/Session 64 - 2009/SVN_64_2009.txt
TXT/Session 64 - 2009/KEN_64_2009.txt
TXT/Session 64 - 2009/MDV_64_2009.txt
TXT/Session 64 - 2009/KHM_64_2009.txt
TXT/Session 64 - 2009/VUT_64_2009.txt
TXT/Session 64 - 2009/KNA_64_2009.txt
TXT/Session 64 - 2009/ISR_64_2009.txt
TXT/Session 64 - 2009/ERI_64_2009.txt
TXT/Session 64 - 2009/CUB_64_2009.txt
TXT/Session 64 - 2009/CHE_64_2009.txt
TXT/Session 64 - 2009/HND_64_2009.txt
TXT/Session 64 - 2009/MKD_64_2009.txt
TXT/Session 64 - 2009/CIV_64_2009.txt
TXT/Session 64 - 2009/SGP_64_2009.txt
TXT/Session 64 - 2009/KOR_64_2009.txt
TXT/Session 51 - 1996/RWA_51_1996.txt
TXT/Session 51 - 1996/JPN_51_1996.txt
TXT/Session 

TXT/Session 27 - 1972/UKR_27_1972.txt
TXT/Session 27 - 1972/ROU_27_1972.txt
TXT/Session 27 - 1972/MWI_27_1972.txt
TXT/Session 27 - 1972/BEN_27_1972.txt
TXT/Session 27 - 1972/GAB_27_1972.txt
TXT/Session 27 - 1972/BHR_27_1972.txt
TXT/Session 27 - 1972/PRY_27_1972.txt
TXT/Session 27 - 1972/THA_27_1972.txt
TXT/Session 27 - 1972/MLT_27_1972.txt
TXT/Session 27 - 1972/IRQ_27_1972.txt
TXT/Session 27 - 1972/JAM_27_1972.txt
TXT/Session 27 - 1972/SOM_27_1972.txt
TXT/Session 27 - 1972/YEM_27_1972.txt
TXT/Session 27 - 1972/NGA_27_1972.txt
TXT/Session 27 - 1972/SEN_27_1972.txt
TXT/Session 27 - 1972/IRN_27_1972.txt
TXT/Session 27 - 1972/YDYE_27_1972.txt
TXT/Session 27 - 1972/KWT_27_1972.txt
TXT/Session 27 - 1972/TZA_27_1972.txt
TXT/Session 27 - 1972/FJI_27_1972.txt
TXT/Session 27 - 1972/NIC_27_1972.txt
TXT/Session 27 - 1972/ITA_27_1972.txt
TXT/Session 27 - 1972/TCD_27_1972.txt
TXT/Session 27 - 1972/ARE_27_1972.txt
TXT/Session 27 - 1972/MMR_27_1972.txt
TXT/Session 27 - 1972/TGO_27_1972.txt
TXT/Session

TXT/Session 70 - 2015/UGA_70_2015.txt
TXT/Session 70 - 2015/NZL_70_2015.txt
TXT/Session 70 - 2015/EGY_70_2015.txt
TXT/Session 70 - 2015/KNA_70_2015.txt
TXT/Session 70 - 2015/VUT_70_2015.txt
TXT/Session 70 - 2015/ISR_70_2015.txt
TXT/Session 70 - 2015/ERI_70_2015.txt
TXT/Session 70 - 2015/CHE_70_2015.txt
TXT/Session 70 - 2015/CUB_70_2015.txt
TXT/Session 70 - 2015/MKD_70_2015.txt
TXT/Session 70 - 2015/HND_70_2015.txt
TXT/Session 70 - 2015/CIV_70_2015.txt
TXT/Session 70 - 2015/KOR_70_2015.txt
TXT/Session 70 - 2015/KEN_70_2015.txt
TXT/Session 70 - 2015/MDV_70_2015.txt
TXT/Session 70 - 2015/KHM_70_2015.txt
TXT/Session 70 - 2015/CHL_70_2015.txt
TXT/Session 70 - 2015/TON_70_2015.txt
TXT/Session 70 - 2015/COL_70_2015.txt
TXT/Session 70 - 2015/DEU_70_2015.txt
TXT/Session 70 - 2015/TLS_70_2015.txt
TXT/Session 70 - 2015/PER_70_2015.txt
TXT/Session 70 - 2015/PSE_70_2015.txt
TXT/Session 70 - 2015/SYC_70_2015.txt
TXT/Session 70 - 2015/SVN_70_2015.txt
TXT/Session 70 - 2015/LTU_70_2015.txt
TXT/Session 

TXT/Session 53 - 1998/ECU_53_1998.txt
TXT/Session 53 - 1998/CRI_53_1998.txt
TXT/Session 53 - 1998/PRT_53_1998.txt
TXT/Session 53 - 1998/BFA_53_1998.txt
TXT/Session 53 - 1998/CHN_53_1998.txt
TXT/Session 53 - 1998/GNB_53_1998.txt
TXT/Session 53 - 1998/BGR_53_1998.txt
TXT/Session 53 - 1998/GBR_53_1998.txt
TXT/Session 53 - 1998/LKA_53_1998.txt
TXT/Session 53 - 1998/POL_53_1998.txt
TXT/Session 53 - 1998/PRK_53_1998.txt
TXT/Session 53 - 1998/PHL_53_1998.txt
TXT/Session 53 - 1998/DZA_53_1998.txt
TXT/Session 53 - 1998/MEX_53_1998.txt
TXT/Session 53 - 1998/AUT_53_1998.txt
TXT/Session 53 - 1998/CYP_53_1998.txt
TXT/Session 53 - 1998/COG_53_1998.txt
TXT/Session 53 - 1998/SLB_53_1998.txt
TXT/Session 53 - 1998/TJK_53_1998.txt
TXT/Session 53 - 1998/ATG_53_1998.txt
TXT/Session 53 - 1998/CAF_53_1998.txt
TXT/Session 53 - 1998/BGD_53_1998.txt
TXT/Session 53 - 1998/BRN_53_1998.txt
TXT/Session 53 - 1998/MYS_53_1998.txt
TXT/Session 53 - 1998/BHS_53_1998.txt
TXT/Session 53 - 1998/GIN_53_1998.txt
TXT/Session 

TXT/Session 38 - 1983/UKR_38_1983.txt
TXT/Session 38 - 1983/LAO_38_1983.txt
TXT/Session 38 - 1983/NPL_38_1983.txt
TXT/Session 38 - 1983/CMR_38_1983.txt
TXT/Session 38 - 1983/LBR_38_1983.txt
TXT/Session 38 - 1983/KWT_38_1983.txt
TXT/Session 38 - 1983/YDYE_38_1983.txt
TXT/Session 38 - 1983/IRN_38_1983.txt
TXT/Session 38 - 1983/NGA_38_1983.txt
TXT/Session 38 - 1983/SEN_38_1983.txt
TXT/Session 38 - 1983/JAM_38_1983.txt
TXT/Session 38 - 1983/SOM_38_1983.txt
TXT/Session 38 - 1983/YEM_38_1983.txt
TXT/Session 38 - 1983/MLT_38_1983.txt
TXT/Session 38 - 1983/IRQ_38_1983.txt
TXT/Session 38 - 1983/HTI_38_1983.txt
TXT/Session 38 - 1983/ESP_38_1983.txt
TXT/Session 38 - 1983/MRT_38_1983.txt
TXT/Session 38 - 1983/CAN_38_1983.txt
TXT/Session 38 - 1983/MAR_38_1983.txt
TXT/Session 38 - 1983/SDN_38_1983.txt
TXT/Session 38 - 1983/MOZ_38_1983.txt
TXT/Session 38 - 1983/GTM_38_1983.txt
TXT/Session 38 - 1983/USA_38_1983.txt
TXT/Session 38 - 1983/QAT_38_1983.txt
TXT/Session 38 - 1983/TTO_38_1983.txt
TXT/Session

TXT/Session 35 - 1980/COM_35_1980.txt
TXT/Session 35 - 1980/ZWE_35_1980.txt
TXT/Session 35 - 1980/VCT_35_1980.txt
TXT/Session 35 - 1980/ZMB_35_1980.txt
TXT/Session 35 - 1980/LUX_35_1980.txt
TXT/Session 35 - 1980/COD_35_1980.txt
TXT/Session 35 - 1980/VEN_35_1980.txt
TXT/Session 35 - 1980/GRC_35_1980.txt
TXT/Session 35 - 1980/ISL_35_1980.txt
TXT/Session 35 - 1980/YUG_35_1980.txt
TXT/Session 35 - 1980/HUN_35_1980.txt
TXT/Session 35 - 1980/GUY_35_1980.txt
TXT/Session 35 - 1980/RWA_35_1980.txt
TXT/Session 35 - 1980/JPN_35_1980.txt
TXT/Session 35 - 1980/GHA_35_1980.txt
TXT/Session 35 - 1980/BEL_35_1980.txt
TXT/Session 35 - 1980/BLR_35_1980.txt
TXT/Session 35 - 1980/MNG_35_1980.txt
TXT/Session 35 - 1980/OMN_35_1980.txt
TXT/Session 35 - 1980/MLI_35_1980.txt
TXT/Session 35 - 1980/PAK_35_1980.txt
TXT/Session 35 - 1980/FRA_35_1980.txt
TXT/Session 35 - 1980/IRL_35_1980.txt
TXT/Session 35 - 1980/MUS_35_1980.txt
TXT/Session 35 - 1980/NER_35_1980.txt
TXT/Session 35 - 1980/BDI_35_1980.txt
TXT/Session 

TXT/Session 26 - 1971/COL_26_1971.txt
TXT/Session 26 - 1971/CHL_26_1971.txt
TXT/Session 26 - 1971/SLV_26_1971.txt
TXT/Session 26 - 1971/FIN_26_1971.txt
TXT/Session 26 - 1971/SAU_26_1971.txt
TXT/Session 26 - 1971/SGP_26_1971.txt
TXT/Session 26 - 1971/CIV_26_1971.txt
TXT/Session 26 - 1971/CUB_26_1971.txt
TXT/Session 26 - 1971/ISR_26_1971.txt
TXT/Session 26 - 1971/KHM_26_1971.txt
TXT/Session 26 - 1971/KEN_26_1971.txt
TXT/Session 26 - 1971/GIN_26_1971.txt
TXT/Session 26 - 1971/IDN_26_1971.txt
TXT/Session 26 - 1971/BOL_26_1971.txt
TXT/Session 26 - 1971/SYR_26_1971.txt
TXT/Session 26 - 1971/RUS_26_1971.txt
TXT/Session 26 - 1971/MDG_26_1971.txt
TXT/Session 26 - 1971/TUN_26_1971.txt
TXT/Session 26 - 1971/NOR_26_1971.txt
TXT/Session 26 - 1971/ALB_26_1971.txt
TXT/Session 26 - 1971/IND_26_1971.txt
TXT/Session 26 - 1971/ARG_26_1971.txt
TXT/Session 26 - 1971/JOR_26_1971.txt
TXT/Session 26 - 1971/SWE_26_1971.txt
TXT/Session 26 - 1971/CHN_26_1971.txt
TXT/Session 26 - 1971/BFA_26_1971.txt
TXT/Session 

TXT/Session 71 - 2016/IRQ_71_2016.txt
TXT/Session 71 - 2016/KWT_71_2016.txt
TXT/Session 71 - 2016/BIH_71_2016.txt
TXT/Session 71 - 2016/MNE_71_2016.txt
TXT/Session 71 - 2016/IRN_71_2016.txt
TXT/Session 71 - 2016/NAM_71_2016.txt
TXT/Session 71 - 2016/GRD_71_2016.txt
TXT/Session 71 - 2016/MWI_71_2016.txt
TXT/Session 71 - 2016/BEN_71_2016.txt
TXT/Session 71 - 2016/LCA_71_2016.txt
TXT/Session 71 - 2016/STP_71_2016.txt
TXT/Session 71 - 2016/ROU_71_2016.txt
TXT/Session 71 - 2016/LAO_71_2016.txt
TXT/Session 71 - 2016/UKR_71_2016.txt
TXT/Session 71 - 2016/VAT_71_2016.txt
TXT/Session 71 - 2016/CMR_71_2016.txt
TXT/Session 71 - 2016/LBR_71_2016.txt
TXT/Session 71 - 2016/NPL_71_2016.txt
TXT/Session 71 - 2016/HRV_71_2016.txt
TXT/Session 71 - 2016/THA_71_2016.txt
TXT/Session 71 - 2016/PRY_71_2016.txt
TXT/Session 71 - 2016/BHR_71_2016.txt
TXT/Session 71 - 2016/AND_71_2016.txt
TXT/Session 71 - 2016/MCO_71_2016.txt
TXT/Session 71 - 2016/GAB_71_2016.txt
TXT/Session 48 - 1993/BIH_48_1993.txt
TXT/Session 

TXT/Session 62 - 2007/BEN_62_2007.txt
TXT/Session 62 - 2007/GRD_62_2007.txt
TXT/Session 62 - 2007/ROU_62_2007.txt
TXT/Session 62 - 2007/STP_62_2007.txt
TXT/Session 62 - 2007/MCO_62_2007.txt
TXT/Session 62 - 2007/AND_62_2007.txt
TXT/Session 62 - 2007/BHR_62_2007.txt
TXT/Session 62 - 2007/GAB_62_2007.txt
TXT/Session 62 - 2007/HRV_62_2007.txt
TXT/Session 62 - 2007/PRY_62_2007.txt
TXT/Session 62 - 2007/THA_62_2007.txt
TXT/Session 62 - 2007/AUS_62_2007.txt
TXT/Session 62 - 2007/NLD_62_2007.txt
TXT/Session 62 - 2007/MMR_62_2007.txt
TXT/Session 62 - 2007/TGO_62_2007.txt
TXT/Session 62 - 2007/SLE_62_2007.txt
TXT/Session 62 - 2007/LBN_62_2007.txt
TXT/Session 62 - 2007/KGZ_62_2007.txt
TXT/Session 62 - 2007/NZL_62_2007.txt
TXT/Session 62 - 2007/EGY_62_2007.txt
TXT/Session 62 - 2007/UGA_62_2007.txt
TXT/Session 62 - 2007/CPV_62_2007.txt
TXT/Session 62 - 2007/FJI_62_2007.txt
TXT/Session 62 - 2007/TZA_62_2007.txt
TXT/Session 62 - 2007/NIC_62_2007.txt
TXT/Session 62 - 2007/SVK_62_2007.txt
TXT/Session 

TXT/Session 75 - 2020/BFA_75_2020.txt
TXT/Session 75 - 2020/DZA_75_2020.txt
TXT/Session 75 - 2020/PHL_75_2020.txt
TXT/Session 75 - 2020/POL_75_2020.txt
TXT/Session 75 - 2020/LKA_75_2020.txt
TXT/Session 75 - 2020/PRK_75_2020.txt
TXT/Session 75 - 2020/TJK_75_2020.txt
TXT/Session 75 - 2020/ATG_75_2020.txt
TXT/Session 75 - 2020/SLB_75_2020.txt
TXT/Session 75 - 2020/CYP_75_2020.txt
TXT/Session 75 - 2020/COG_75_2020.txt
TXT/Session 75 - 2020/MEX_75_2020.txt
TXT/Session 75 - 2020/AUT_75_2020.txt
TXT/Session 75 - 2020/MYS_75_2020.txt
TXT/Session 75 - 2020/CAF_75_2020.txt
TXT/Session 75 - 2020/BGD_75_2020.txt
TXT/Session 75 - 2020/LBN_75_2020.txt
TXT/Session 75 - 2020/KGZ_75_2020.txt
TXT/Session 75 - 2020/SLE_75_2020.txt
TXT/Session 75 - 2020/MMR_75_2020.txt
TXT/Session 75 - 2020/TGO_75_2020.txt
TXT/Session 75 - 2020/NLD_75_2020.txt
TXT/Session 75 - 2020/AUS_75_2020.txt
TXT/Session 75 - 2020/UGA_75_2020.txt
TXT/Session 75 - 2020/CPV_75_2020.txt
TXT/Session 75 - 2020/EGY_75_2020.txt
TXT/Session 

TXT/Session 45 - 1990/BRA_45_1990.txt
TXT/Session 45 - 1990/LBY_45_1990.txt
TXT/Session 45 - 1990/GUY_45_1990.txt
TXT/Session 45 - 1990/JPN_45_1990.txt
TXT/Session 45 - 1990/RWA_45_1990.txt
TXT/Session 45 - 1990/WSM_45_1990.txt
TXT/Session 45 - 1990/GHA_45_1990.txt
TXT/Session 45 - 1990/BEL_45_1990.txt
TXT/Session 45 - 1990/BLR_45_1990.txt
TXT/Session 45 - 1990/BOL_45_1990.txt
TXT/Session 45 - 1990/GNQ_45_1990.txt
TXT/Session 45 - 1990/SYR_45_1990.txt
TXT/Session 45 - 1990/IDN_45_1990.txt
TXT/Session 45 - 1990/DJI_45_1990.txt
TXT/Session 45 - 1990/RUS_45_1990.txt
TXT/Session 45 - 1990/GIN_45_1990.txt
TXT/Session 45 - 1990/BHS_45_1990.txt
TXT/Session 45 - 1990/DNK_45_1990.txt
TXT/Session 45 - 1990/BRB_45_1990.txt
TXT/Session 45 - 1990/JOR_45_1990.txt
TXT/Session 45 - 1990/SWE_45_1990.txt
TXT/Session 45 - 1990/IND_45_1990.txt
TXT/Session 45 - 1990/ARG_45_1990.txt
TXT/Session 45 - 1990/MDG_45_1990.txt
TXT/Session 45 - 1990/SWZ_45_1990.txt
TXT/Session 45 - 1990/ALB_45_1990.txt
TXT/Session 

TXT/Session 59 - 2004/YEM_59_2004.txt
TXT/Session 59 - 2004/JAM_59_2004.txt
TXT/Session 59 - 2004/SEN_59_2004.txt
TXT/Session 59 - 2004/NGA_59_2004.txt
TXT/Session 59 - 2004/DMA_59_2004.txt
TXT/Session 59 - 2004/GAB_59_2004.txt
TXT/Session 59 - 2004/MCO_59_2004.txt
TXT/Session 59 - 2004/AND_59_2004.txt
TXT/Session 59 - 2004/BHR_59_2004.txt
TXT/Session 59 - 2004/PRY_59_2004.txt
TXT/Session 59 - 2004/THA_59_2004.txt
TXT/Session 59 - 2004/HRV_59_2004.txt
TXT/Session 59 - 2004/NPL_59_2004.txt
TXT/Session 59 - 2004/LBR_59_2004.txt
TXT/Session 59 - 2004/CMR_59_2004.txt
TXT/Session 59 - 2004/VAT_59_2004.txt
TXT/Session 59 - 2004/UKR_59_2004.txt
TXT/Session 59 - 2004/LAO_59_2004.txt
TXT/Session 59 - 2004/ROU_59_2004.txt
TXT/Session 59 - 2004/STP_59_2004.txt
TXT/Session 59 - 2004/LCA_59_2004.txt
TXT/Session 59 - 2004/BEN_59_2004.txt
TXT/Session 59 - 2004/MWI_59_2004.txt
TXT/Session 59 - 2004/GRD_59_2004.txt
TXT/Session 68 - 2013/MHL_68_2013.txt
TXT/Session 68 - 2013/CAN_68_2013.txt
TXT/Session 

TXT/Session 42 - 1987/JAM_42_1987.txt
TXT/Session 42 - 1987/SOM_42_1987.txt
TXT/Session 42 - 1987/YEM_42_1987.txt
TXT/Session 42 - 1987/NGA_42_1987.txt
TXT/Session 42 - 1987/SEN_42_1987.txt
TXT/Session 42 - 1987/ESP_42_1987.txt
TXT/Session 42 - 1987/MRT_42_1987.txt
TXT/Session 42 - 1987/HTI_42_1987.txt
TXT/Session 42 - 1987/MAR_42_1987.txt
TXT/Session 42 - 1987/CAN_42_1987.txt
TXT/Session 42 - 1987/QAT_42_1987.txt
TXT/Session 42 - 1987/USA_42_1987.txt
TXT/Session 42 - 1987/GTM_42_1987.txt
TXT/Session 42 - 1987/MOZ_42_1987.txt
TXT/Session 42 - 1987/SDN_42_1987.txt
TXT/Session 42 - 1987/BWA_42_1987.txt
TXT/Session 42 - 1987/TTO_42_1987.txt
TXT/Session 42 - 1987/MDV_42_1987.txt
TXT/Session 42 - 1987/KHM_42_1987.txt
TXT/Session 42 - 1987/KEN_42_1987.txt
TXT/Session 42 - 1987/SGP_42_1987.txt
TXT/Session 42 - 1987/HND_42_1987.txt
TXT/Session 42 - 1987/CUB_42_1987.txt
TXT/Session 42 - 1987/KNA_42_1987.txt
TXT/Session 42 - 1987/VUT_42_1987.txt
TXT/Session 42 - 1987/ISR_42_1987.txt
TXT/Session 

TXT/Session 56 - 2001/POL_56_2001.txt
TXT/Session 56 - 2001/LKA_56_2001.txt
TXT/Session 56 - 2001/PRK_56_2001.txt
TXT/Session 56 - 2001/BGR_56_2001.txt
TXT/Session 56 - 2001/GBR_56_2001.txt
TXT/Session 56 - 2001/GNB_56_2001.txt
TXT/Session 56 - 2001/CHN_56_2001.txt
TXT/Session 56 - 2001/ECU_56_2001.txt
TXT/Session 56 - 2001/CRI_56_2001.txt
TXT/Session 56 - 2001/BFA_56_2001.txt
TXT/Session 56 - 2001/PRT_56_2001.txt
TXT/Session 56 - 2001/ARG_56_2001.txt
TXT/Session 56 - 2001/IND_56_2001.txt
TXT/Session 56 - 2001/SWE_56_2001.txt
TXT/Session 56 - 2001/JOR_56_2001.txt
TXT/Session 56 - 2001/BRB_56_2001.txt
TXT/Session 56 - 2001/NRU_56_2001.txt
TXT/Session 56 - 2001/TUN_56_2001.txt
TXT/Session 56 - 2001/NOR_56_2001.txt
TXT/Session 56 - 2001/BTN_56_2001.txt
TXT/Session 56 - 2001/ALB_56_2001.txt
TXT/Session 56 - 2001/SWZ_56_2001.txt
TXT/Session 56 - 2001/MDG_56_2001.txt
TXT/Session 56 - 2001/EST_56_2001.txt
TXT/Session 56 - 2001/RUS_56_2001.txt
TXT/Session 56 - 2001/DJI_56_2001.txt
TXT/Session 

TXT/Session 65 - 2010/GNB_65_2010.txt
TXT/Session 65 - 2010/PHL_65_2010.txt
TXT/Session 65 - 2010/POL_65_2010.txt
TXT/Session 65 - 2010/LKA_65_2010.txt
TXT/Session 65 - 2010/PRK_65_2010.txt
TXT/Session 65 - 2010/DZA_65_2010.txt
TXT/Session 65 - 2010/EST_65_2010.txt
TXT/Session 65 - 2010/NRU_65_2010.txt
TXT/Session 65 - 2010/TUN_65_2010.txt
TXT/Session 65 - 2010/NOR_65_2010.txt
TXT/Session 65 - 2010/BTN_65_2010.txt
TXT/Session 65 - 2010/ALB_65_2010.txt
TXT/Session 65 - 2010/SWZ_65_2010.txt
TXT/Session 65 - 2010/BRB_65_2010.txt
TXT/Session 65 - 2010/ARG_65_2010.txt
TXT/Session 65 - 2010/IND_65_2010.txt
TXT/Session 65 - 2010/SWE_65_2010.txt
TXT/Session 65 - 2010/JOR_65_2010.txt
TXT/Session 65 - 2010/BHS_65_2010.txt
TXT/Session 65 - 2010/GIN_65_2010.txt
TXT/Session 65 - 2010/DNK_65_2010.txt
TXT/Session 65 - 2010/IDN_65_2010.txt
TXT/Session 65 - 2010/SYR_65_2010.txt
TXT/Session 65 - 2010/GNQ_65_2010.txt
TXT/Session 65 - 2010/SRB_65_2010.txt
TXT/Session 65 - 2010/BOL_65_2010.txt
TXT/Session 

TXT/Session 57 - 2002/PER_57_2002.txt
TXT/Session 57 - 2002/KEN_57_2002.txt
TXT/Session 57 - 2002/KHM_57_2002.txt
TXT/Session 57 - 2002/MDV_57_2002.txt
TXT/Session 57 - 2002/CHE_57_2002.txt
TXT/Session 57 - 2002/CUB_57_2002.txt
TXT/Session 57 - 2002/ERI_57_2002.txt
TXT/Session 57 - 2002/ISR_57_2002.txt
TXT/Session 57 - 2002/KNA_57_2002.txt
TXT/Session 57 - 2002/VUT_57_2002.txt
TXT/Session 57 - 2002/KOR_57_2002.txt
TXT/Session 57 - 2002/SGP_57_2002.txt
TXT/Session 57 - 2002/CIV_57_2002.txt
TXT/Session 57 - 2002/MKD_57_2002.txt
TXT/Session 57 - 2002/HND_57_2002.txt
TXT/Session 57 - 2002/UGA_57_2002.txt
TXT/Session 57 - 2002/CPV_57_2002.txt
TXT/Session 57 - 2002/EGY_57_2002.txt
TXT/Session 57 - 2002/NZL_57_2002.txt
TXT/Session 57 - 2002/LBN_57_2002.txt
TXT/Session 57 - 2002/KGZ_57_2002.txt
TXT/Session 57 - 2002/SLE_57_2002.txt
TXT/Session 57 - 2002/MMR_57_2002.txt
TXT/Session 57 - 2002/TGO_57_2002.txt
TXT/Session 57 - 2002/NLD_57_2002.txt
TXT/Session 57 - 2002/AUS_57_2002.txt
TXT/Session 

TXT/Session 72 - 2017/GHA_72_2017.txt
TXT/Session 72 - 2017/WSM_72_2017.txt
TXT/Session 72 - 2017/ARM_72_2017.txt
TXT/Session 72 - 2017/BLR_72_2017.txt
TXT/Session 72 - 2017/OMN_72_2017.txt
TXT/Session 72 - 2017/SSD_72_2017.txt
TXT/Session 72 - 2017/MNG_72_2017.txt
TXT/Session 72 - 2017/BDI_72_2017.txt
TXT/Session 72 - 2017/VNM_72_2017.txt
TXT/Session 72 - 2017/IRL_72_2017.txt
TXT/Session 72 - 2017/MUS_72_2017.txt
TXT/Session 72 - 2017/NER_72_2017.txt
TXT/Session 72 - 2017/PAK_72_2017.txt
TXT/Session 72 - 2017/MLI_72_2017.txt
TXT/Session 72 - 2017/FRA_72_2017.txt
TXT/Session 72 - 2017/FSM_72_2017.txt
TXT/Session 72 - 2017/TUR_72_2017.txt
TXT/Session 72 - 2017/PLW_72_2017.txt
TXT/Session 72 - 2017/LBY_72_2017.txt
TXT/Session 72 - 2017/BRA_72_2017.txt
TXT/Session 72 - 2017/EU_72_2017.txt
TXT/Session 72 - 2017/ETH_72_2017.txt
TXT/Session 72 - 2017/DOM_72_2017.txt
TXT/Session 72 - 2017/URY_72_2017.txt
TXT/Session 72 - 2017/PAN_72_2017.txt
TXT/Session 72 - 2017/SUR_72_2017.txt
TXT/Session 7

TXT/Session 36 - 1981/JPN_36_1981.txt
TXT/Session 36 - 1981/GUY_36_1981.txt
TXT/Session 36 - 1981/YUG_36_1981.txt
TXT/Session 36 - 1981/ISL_36_1981.txt
TXT/Session 36 - 1981/HUN_36_1981.txt
TXT/Session 36 - 1981/GRC_36_1981.txt
TXT/Session 36 - 1981/VEN_36_1981.txt
TXT/Session 36 - 1981/COD_36_1981.txt
TXT/Session 36 - 1981/LUX_36_1981.txt
TXT/Session 36 - 1981/ZMB_36_1981.txt
TXT/Session 36 - 1981/VCT_36_1981.txt
TXT/Session 36 - 1981/ZWE_36_1981.txt
TXT/Session 36 - 1981/COM_36_1981.txt
TXT/Session 36 - 1981/SUR_36_1981.txt
TXT/Session 36 - 1981/PAN_36_1981.txt
TXT/Session 36 - 1981/URY_36_1981.txt
TXT/Session 36 - 1981/AFG_36_1981.txt
TXT/Session 36 - 1981/SEN_36_1981.txt
TXT/Session 36 - 1981/DMA_36_1981.txt
TXT/Session 36 - 1981/NGA_36_1981.txt
TXT/Session 36 - 1981/IRQ_36_1981.txt
TXT/Session 36 - 1981/MLT_36_1981.txt
TXT/Session 36 - 1981/SOM_36_1981.txt
TXT/Session 36 - 1981/YEM_36_1981.txt
TXT/Session 36 - 1981/JAM_36_1981.txt
TXT/Session 36 - 1981/YDYE_36_1981.txt
TXT/Session

TXT/Session 37 - 1982/ITA_37_1982.txt
TXT/Session 37 - 1982/ARE_37_1982.txt
TXT/Session 37 - 1982/TCD_37_1982.txt
TXT/Session 37 - 1982/SLE_37_1982.txt
TXT/Session 37 - 1982/MMR_37_1982.txt
TXT/Session 37 - 1982/TGO_37_1982.txt
TXT/Session 37 - 1982/AUS_37_1982.txt
TXT/Session 37 - 1982/NLD_37_1982.txt
TXT/Session 37 - 1982/UGA_37_1982.txt
TXT/Session 37 - 1982/CPV_37_1982.txt
TXT/Session 37 - 1982/CSK_37_1982.txt
TXT/Session 37 - 1982/EGY_37_1982.txt
TXT/Session 37 - 1982/NZL_37_1982.txt
TXT/Session 28 - 1973/AFG_28_1973.txt
TXT/Session 28 - 1973/URY_28_1973.txt
TXT/Session 28 - 1973/PAN_28_1973.txt
TXT/Session 28 - 1973/LUX_28_1973.txt
TXT/Session 28 - 1973/ZMB_28_1973.txt
TXT/Session 28 - 1973/COD_28_1973.txt
TXT/Session 28 - 1973/VEN_28_1973.txt
TXT/Session 28 - 1973/GRC_28_1973.txt
TXT/Session 28 - 1973/ISL_28_1973.txt
TXT/Session 28 - 1973/YUG_28_1973.txt
TXT/Session 28 - 1973/HUN_28_1973.txt
TXT/Session 28 - 1973/GUY_28_1973.txt
TXT/Session 28 - 1973/RWA_28_1973.txt
TXT/Session 

TXT/Session 52 - 1997/ZWE_52_1997.txt
TXT/Session 52 - 1997/TKM_52_1997.txt
TXT/Session 52 - 1997/LUX_52_1997.txt
TXT/Session 52 - 1997/ZMB_52_1997.txt
TXT/Session 52 - 1997/MDA_52_1997.txt
TXT/Session 52 - 1997/AFG_52_1997.txt
TXT/Session 52 - 1997/SUR_52_1997.txt
TXT/Session 52 - 1997/PAN_52_1997.txt
TXT/Session 52 - 1997/URY_52_1997.txt
TXT/Session 52 - 1997/COM_52_1997.txt
TXT/Session 52 - 1997/TUR_52_1997.txt
TXT/Session 52 - 1997/DOM_52_1997.txt
TXT/Session 52 - 1997/ETH_52_1997.txt
TXT/Session 52 - 1997/BRA_52_1997.txt
TXT/Session 52 - 1997/LBY_52_1997.txt
TXT/Session 52 - 1997/MNG_52_1997.txt
TXT/Session 52 - 1997/OMN_52_1997.txt
TXT/Session 52 - 1997/FRA_52_1997.txt
TXT/Session 52 - 1997/MLI_52_1997.txt
TXT/Session 52 - 1997/PAK_52_1997.txt
TXT/Session 52 - 1997/NER_52_1997.txt
TXT/Session 52 - 1997/MUS_52_1997.txt
TXT/Session 52 - 1997/IRL_52_1997.txt
TXT/Session 52 - 1997/VNM_52_1997.txt
TXT/Session 52 - 1997/BDI_52_1997.txt
TXT/Session 52 - 1997/ARM_52_1997.txt
TXT/Session 

TXT/Session 39 - 1984/GNB_39_1984.txt
TXT/Session 39 - 1984/PHL_39_1984.txt
TXT/Session 39 - 1984/POL_39_1984.txt
TXT/Session 39 - 1984/LKA_39_1984.txt
TXT/Session 39 - 1984/DZA_39_1984.txt
TXT/Session 58 - 2003/ETH_58_2003.txt
TXT/Session 58 - 2003/DOM_58_2003.txt
TXT/Session 58 - 2003/BRA_58_2003.txt
TXT/Session 58 - 2003/PLW_58_2003.txt
TXT/Session 58 - 2003/FSM_58_2003.txt
TXT/Session 58 - 2003/TUR_58_2003.txt
TXT/Session 58 - 2003/IRL_58_2003.txt
TXT/Session 58 - 2003/NER_58_2003.txt
TXT/Session 58 - 2003/MUS_58_2003.txt
TXT/Session 58 - 2003/MLI_58_2003.txt
TXT/Session 58 - 2003/PAK_58_2003.txt
TXT/Session 58 - 2003/FRA_58_2003.txt
TXT/Session 58 - 2003/BDI_58_2003.txt
TXT/Session 58 - 2003/VNM_58_2003.txt
TXT/Session 58 - 2003/MNG_58_2003.txt
TXT/Session 58 - 2003/OMN_58_2003.txt
TXT/Session 58 - 2003/BLR_58_2003.txt
TXT/Session 58 - 2003/GHA_58_2003.txt
TXT/Session 58 - 2003/WSM_58_2003.txt
TXT/Session 58 - 2003/ARM_58_2003.txt
TXT/Session 58 - 2003/BEL_58_2003.txt
TXT/Session 

TXT/Session 31 - 1976/BEN_31_1976.txt
TXT/Session 31 - 1976/GRD_31_1976.txt
TXT/Session 31 - 1976/EGY_31_1976.txt
TXT/Session 31 - 1976/NZL_31_1976.txt
TXT/Session 31 - 1976/UGA_31_1976.txt
TXT/Session 31 - 1976/CPV_31_1976.txt
TXT/Session 31 - 1976/CSK_31_1976.txt
TXT/Session 31 - 1976/TGO_31_1976.txt
TXT/Session 31 - 1976/MMR_31_1976.txt
TXT/Session 31 - 1976/AUS_31_1976.txt
TXT/Session 31 - 1976/NLD_31_1976.txt
TXT/Session 31 - 1976/LBN_31_1976.txt
TXT/Session 31 - 1976/SLE_31_1976.txt
TXT/Session 31 - 1976/ITA_31_1976.txt
TXT/Session 31 - 1976/ARE_31_1976.txt
TXT/Session 31 - 1976/TCD_31_1976.txt
TXT/Session 31 - 1976/LSO_31_1976.txt
TXT/Session 31 - 1976/FJI_31_1976.txt
TXT/Session 31 - 1976/TZA_31_1976.txt
TXT/Session 31 - 1976/PNG_31_1976.txt
TXT/Session 31 - 1976/NIC_31_1976.txt
TXT/Session 31 - 1976/SLV_31_1976.txt
TXT/Session 31 - 1976/FIN_31_1976.txt
TXT/Session 31 - 1976/SAU_31_1976.txt
TXT/Session 31 - 1976/PER_31_1976.txt
TXT/Session 31 - 1976/DEU_31_1976.txt
TXT/Session 

TXT/Session 66 - 2011/KNA_66_2011.txt
TXT/Session 66 - 2011/VUT_66_2011.txt
TXT/Session 66 - 2011/CUB_66_2011.txt
TXT/Session 66 - 2011/CHE_66_2011.txt
TXT/Session 66 - 2011/ERI_66_2011.txt
TXT/Session 66 - 2011/CIV_66_2011.txt
TXT/Session 66 - 2011/MKD_66_2011.txt
TXT/Session 66 - 2011/HND_66_2011.txt
TXT/Session 66 - 2011/KOR_66_2011.txt
TXT/Session 66 - 2011/SGP_66_2011.txt
TXT/Session 66 - 2011/MOZ_66_2011.txt
TXT/Session 66 - 2011/SDN_66_2011.txt
TXT/Session 66 - 2011/GTM_66_2011.txt
TXT/Session 66 - 2011/USA_66_2011.txt
TXT/Session 66 - 2011/ZAF_66_2011.txt
TXT/Session 66 - 2011/QAT_66_2011.txt
TXT/Session 66 - 2011/TTO_66_2011.txt
TXT/Session 66 - 2011/BWA_66_2011.txt
TXT/Session 66 - 2011/HTI_66_2011.txt
TXT/Session 66 - 2011/MRT_66_2011.txt
TXT/Session 66 - 2011/ESP_66_2011.txt
TXT/Session 66 - 2011/CZE_66_2011.txt
TXT/Session 66 - 2011/CAN_66_2011.txt
TXT/Session 66 - 2011/MHL_66_2011.txt
TXT/Session 66 - 2011/MAR_66_2011.txt
TXT/Session 66 - 2011/BIH_66_2011.txt
TXT/Session 

TXT/Session 40 - 1985/TUN_40_1985.txt
TXT/Session 40 - 1985/NOR_40_1985.txt
TXT/Session 40 - 1985/MDG_40_1985.txt
TXT/Session 40 - 1985/JOR_40_1985.txt
TXT/Session 40 - 1985/SWE_40_1985.txt
TXT/Session 40 - 1985/IND_40_1985.txt
TXT/Session 40 - 1985/ARG_40_1985.txt
TXT/Session 40 - 1985/BRB_40_1985.txt
TXT/Session 40 - 1985/DNK_40_1985.txt
TXT/Session 40 - 1985/GIN_40_1985.txt
TXT/Session 40 - 1985/BHS_40_1985.txt
TXT/Session 40 - 1985/DJI_40_1985.txt
TXT/Session 40 - 1985/RUS_40_1985.txt
TXT/Session 40 - 1985/BOL_40_1985.txt
TXT/Session 40 - 1985/SYR_40_1985.txt
TXT/Session 40 - 1985/IDN_40_1985.txt
TXT/Session 40 - 1985/SLB_40_1985.txt
TXT/Session 40 - 1985/AUT_40_1985.txt
TXT/Session 40 - 1985/MEX_40_1985.txt
TXT/Session 40 - 1985/COG_40_1985.txt
TXT/Session 40 - 1985/CYP_40_1985.txt
TXT/Session 40 - 1985/DDR_40_1985.txt
TXT/Session 40 - 1985/BGD_40_1985.txt
TXT/Session 40 - 1985/CAF_40_1985.txt
TXT/Session 40 - 1985/MYS_40_1985.txt
TXT/Session 40 - 1985/BRN_40_1985.txt
TXT/Session 

TXT/Session 55 - 2000/CAN_55_2000.txt
TXT/Session 55 - 2000/MHL_55_2000.txt
TXT/Session 55 - 2000/CZE_55_2000.txt
TXT/Session 55 - 2000/HTI_55_2000.txt
TXT/Session 55 - 2000/MRT_55_2000.txt
TXT/Session 55 - 2000/ESP_55_2000.txt
TXT/Session 55 - 2000/SOM_55_2000.txt
TXT/Session 55 - 2000/YEM_55_2000.txt
TXT/Session 55 - 2000/JAM_55_2000.txt
TXT/Session 55 - 2000/IRQ_55_2000.txt
TXT/Session 55 - 2000/MLT_55_2000.txt
TXT/Session 55 - 2000/SEN_55_2000.txt
TXT/Session 55 - 2000/DMA_55_2000.txt
TXT/Session 55 - 2000/NGA_55_2000.txt
TXT/Session 55 - 2000/NAM_55_2000.txt
TXT/Session 55 - 2000/IRN_55_2000.txt
TXT/Session 55 - 2000/BIH_55_2000.txt
TXT/Session 55 - 2000/KWT_55_2000.txt
TXT/Session 55 - 2000/UKR_55_2000.txt
TXT/Session 55 - 2000/LAO_55_2000.txt
TXT/Session 55 - 2000/NPL_55_2000.txt
TXT/Session 55 - 2000/LBR_55_2000.txt
TXT/Session 55 - 2000/LCA_55_2000.txt
TXT/Session 55 - 2000/BEN_55_2000.txt
TXT/Session 55 - 2000/MWI_55_2000.txt
TXT/Session 55 - 2000/GRD_55_2000.txt
TXT/Session 

TXT/Session 49 - 1994/CMR_49_1994.txt
TXT/Session 49 - 1994/UKR_49_1994.txt
TXT/Session 49 - 1994/LAO_49_1994.txt
TXT/Session 49 - 1994/ROU_49_1994.txt
TXT/Session 49 - 1994/GRD_49_1994.txt
TXT/Session 49 - 1994/BEN_49_1994.txt
TXT/Session 49 - 1994/LCA_49_1994.txt
TXT/Session 49 - 1994/MWI_49_1994.txt
TXT/Session 49 - 1994/GAB_49_1994.txt
TXT/Session 49 - 1994/AND_49_1994.txt
TXT/Session 49 - 1994/BHR_49_1994.txt
TXT/Session 49 - 1994/MCO_49_1994.txt
TXT/Session 49 - 1994/THA_49_1994.txt
TXT/Session 49 - 1994/PRY_49_1994.txt
TXT/Session 49 - 1994/HRV_49_1994.txt
TXT/Session 49 - 1994/TGO_49_1994.txt
TXT/Session 49 - 1994/MMR_49_1994.txt
TXT/Session 49 - 1994/NLD_49_1994.txt
TXT/Session 49 - 1994/AUS_49_1994.txt
TXT/Session 49 - 1994/KGZ_49_1994.txt
TXT/Session 49 - 1994/LBN_49_1994.txt
TXT/Session 49 - 1994/SLE_49_1994.txt
TXT/Session 49 - 1994/EGY_49_1994.txt
TXT/Session 49 - 1994/NZL_49_1994.txt
TXT/Session 49 - 1994/CPV_49_1994.txt
TXT/Session 49 - 1994/UGA_49_1994.txt
TXT/Session 

TXT/Session 67 - 2012/ECU_67_2012.txt
TXT/Session 67 - 2012/BFA_67_2012.txt
TXT/Session 67 - 2012/PRT_67_2012.txt
TXT/Session 67 - 2012/CRI_67_2012.txt
TXT/Session 67 - 2012/CHN_67_2012.txt
TXT/Session 67 - 2012/LSO_67_2012.txt
TXT/Session 67 - 2012/BLZ_67_2012.txt
TXT/Session 67 - 2012/ARE_67_2012.txt
TXT/Session 67 - 2012/LVA_67_2012.txt
TXT/Session 67 - 2012/TCD_67_2012.txt
TXT/Session 67 - 2012/KIR_67_2012.txt
TXT/Session 67 - 2012/ITA_67_2012.txt
TXT/Session 67 - 2012/AGO_67_2012.txt
TXT/Session 67 - 2012/NIC_67_2012.txt
TXT/Session 67 - 2012/SVK_67_2012.txt
TXT/Session 67 - 2012/PNG_67_2012.txt
TXT/Session 67 - 2012/FJI_67_2012.txt
TXT/Session 67 - 2012/TZA_67_2012.txt
TXT/Session 67 - 2012/UGA_67_2012.txt
TXT/Session 67 - 2012/CPV_67_2012.txt
TXT/Session 67 - 2012/NZL_67_2012.txt
TXT/Session 67 - 2012/EGY_67_2012.txt
TXT/Session 67 - 2012/SLE_67_2012.txt
TXT/Session 67 - 2012/LBN_67_2012.txt
TXT/Session 67 - 2012/KGZ_67_2012.txt
TXT/Session 67 - 2012/NLD_67_2012.txt
TXT/Session 

TXT/Session 41 - 1986/PRY_41_1986.txt
TXT/Session 41 - 1986/THA_41_1986.txt
TXT/Session 41 - 1986/BHR_41_1986.txt
TXT/Session 41 - 1986/SLE_41_1986.txt
TXT/Session 41 - 1986/LBN_41_1986.txt
TXT/Session 41 - 1986/NLD_41_1986.txt
TXT/Session 41 - 1986/AUS_41_1986.txt
TXT/Session 41 - 1986/MMR_41_1986.txt
TXT/Session 41 - 1986/TGO_41_1986.txt
TXT/Session 41 - 1986/CSK_41_1986.txt
TXT/Session 41 - 1986/CPV_41_1986.txt
TXT/Session 41 - 1986/NZL_41_1986.txt
TXT/Session 41 - 1986/EGY_41_1986.txt
TXT/Session 41 - 1986/NIC_41_1986.txt
TXT/Session 41 - 1986/PNG_41_1986.txt
TXT/Session 41 - 1986/TZA_41_1986.txt
TXT/Session 41 - 1986/FJI_41_1986.txt
TXT/Session 41 - 1986/BLZ_41_1986.txt
TXT/Session 41 - 1986/LSO_41_1986.txt
TXT/Session 41 - 1986/TCD_41_1986.txt
TXT/Session 41 - 1986/ARE_41_1986.txt
TXT/Session 41 - 1986/AGO_41_1986.txt
TXT/Session 41 - 1986/ITA_41_1986.txt
TXT/Session 41 - 1986/CHL_41_1986.txt
TXT/Session 41 - 1986/DEU_41_1986.txt
TXT/Session 41 - 1986/COL_41_1986.txt
TXT/Session 

TXT/Session 74 - 2019/MRT_74_2019.txt
TXT/Session 74 - 2019/ESP_74_2019.txt
TXT/Session 74 - 2019/HTI_74_2019.txt
TXT/Session 74 - 2019/CZE_74_2019.txt
TXT/Session 74 - 2019/TTO_74_2019.txt
TXT/Session 74 - 2019/BWA_74_2019.txt
TXT/Session 74 - 2019/GTM_74_2019.txt
TXT/Session 74 - 2019/SDN_74_2019.txt
TXT/Session 74 - 2019/MOZ_74_2019.txt
TXT/Session 74 - 2019/QAT_74_2019.txt
TXT/Session 74 - 2019/ZAF_74_2019.txt
TXT/Session 74 - 2019/USA_74_2019.txt
TXT/Session 60 - 2005/DZA_60_2005.txt
TXT/Session 60 - 2005/PHL_60_2005.txt
TXT/Session 60 - 2005/PRK_60_2005.txt
TXT/Session 60 - 2005/POL_60_2005.txt
TXT/Session 60 - 2005/LKA_60_2005.txt
TXT/Session 60 - 2005/BGR_60_2005.txt
TXT/Session 60 - 2005/GBR_60_2005.txt
TXT/Session 60 - 2005/GNB_60_2005.txt
TXT/Session 60 - 2005/CHN_60_2005.txt
TXT/Session 60 - 2005/ECU_60_2005.txt
TXT/Session 60 - 2005/BFA_60_2005.txt
TXT/Session 60 - 2005/PRT_60_2005.txt
TXT/Session 60 - 2005/CRI_60_2005.txt
TXT/Session 60 - 2005/BRN_60_2005.txt
TXT/Session 

TXT/Session 46 - 1991/LUX_46_1991.txt
TXT/Session 46 - 1991/ZMB_46_1991.txt
TXT/Session 46 - 1991/VCT_46_1991.txt
TXT/Session 46 - 1991/ZWE_46_1991.txt
TXT/Session 46 - 1991/COM_46_1991.txt
TXT/Session 46 - 1991/URY_46_1991.txt
TXT/Session 46 - 1991/PAN_46_1991.txt
TXT/Session 46 - 1991/SUR_46_1991.txt
TXT/Session 46 - 1991/AFG_46_1991.txt
TXT/Session 46 - 1991/HUN_46_1991.txt
TXT/Session 46 - 1991/YUG_46_1991.txt
TXT/Session 46 - 1991/ISL_46_1991.txt
TXT/Session 46 - 1991/GRC_46_1991.txt
TXT/Session 46 - 1991/VEN_46_1991.txt
TXT/Session 46 - 1991/LIE_46_1991.txt
TXT/Session 46 - 1991/ATG_46_1991.txt
TXT/Session 46 - 1991/SLB_46_1991.txt
TXT/Session 46 - 1991/CYP_46_1991.txt
TXT/Session 46 - 1991/COG_46_1991.txt
TXT/Session 46 - 1991/AUT_46_1991.txt
TXT/Session 46 - 1991/MEX_46_1991.txt
TXT/Session 46 - 1991/MYS_46_1991.txt
TXT/Session 46 - 1991/BRN_46_1991.txt
TXT/Session 46 - 1991/BGD_46_1991.txt
TXT/Session 46 - 1991/CAF_46_1991.txt
TXT/Session 46 - 1991/BGR_46_1991.txt
TXT/Session 

TXT/Session 43 - 1988/ARE_43_1988.txt
TXT/Session 43 - 1988/BLZ_43_1988.txt
TXT/Session 43 - 1988/LSO_43_1988.txt
TXT/Session 43 - 1988/TZA_43_1988.txt
TXT/Session 43 - 1988/FJI_43_1988.txt
TXT/Session 43 - 1988/PNG_43_1988.txt
TXT/Session 43 - 1988/NIC_43_1988.txt
TXT/Session 43 - 1988/EGY_43_1988.txt
TXT/Session 43 - 1988/NZL_43_1988.txt
TXT/Session 43 - 1988/CPV_43_1988.txt
TXT/Session 43 - 1988/UGA_43_1988.txt
TXT/Session 43 - 1988/CSK_43_1988.txt
TXT/Session 43 - 1988/TGO_43_1988.txt
TXT/Session 43 - 1988/MMR_43_1988.txt
TXT/Session 43 - 1988/NLD_43_1988.txt
TXT/Session 43 - 1988/AUS_43_1988.txt
TXT/Session 43 - 1988/LBN_43_1988.txt
TXT/Session 43 - 1988/SLE_43_1988.txt
TXT/Session 43 - 1988/MDV_43_1988.txt
TXT/Session 43 - 1988/KHM_43_1988.txt
TXT/Session 43 - 1988/KEN_43_1988.txt
TXT/Session 43 - 1988/SGP_43_1988.txt
TXT/Session 43 - 1988/HND_43_1988.txt
TXT/Session 43 - 1988/CUB_43_1988.txt
TXT/Session 43 - 1988/VUT_43_1988.txt
TXT/Session 43 - 1988/KNA_43_1988.txt
TXT/Session 

TXT/Session 61 - 2006/GMB_61_2006.txt
TXT/Session 61 - 2006/SLV_61_2006.txt
TXT/Session 61 - 2006/TLS_61_2006.txt
TXT/Session 61 - 2006/COL_61_2006.txt
TXT/Session 61 - 2006/DEU_61_2006.txt
TXT/Session 61 - 2006/CHL_61_2006.txt
TXT/Session 61 - 2006/TON_61_2006.txt
TXT/Session 61 - 2006/LTU_61_2006.txt
TXT/Session 61 - 2006/SVN_61_2006.txt
TXT/Session 61 - 2006/SYC_61_2006.txt
TXT/Session 61 - 2006/PSE_61_2006.txt
TXT/Session 61 - 2006/PER_61_2006.txt
TXT/Session 61 - 2006/LSO_61_2006.txt
TXT/Session 61 - 2006/BLZ_61_2006.txt
TXT/Session 61 - 2006/KIR_61_2006.txt
TXT/Session 61 - 2006/ITA_61_2006.txt
TXT/Session 61 - 2006/AGO_61_2006.txt
TXT/Session 61 - 2006/ARE_61_2006.txt
TXT/Session 61 - 2006/LVA_61_2006.txt
TXT/Session 61 - 2006/TCD_61_2006.txt
TXT/Session 61 - 2006/PNG_61_2006.txt
TXT/Session 61 - 2006/NIC_61_2006.txt
TXT/Session 61 - 2006/SVK_61_2006.txt
TXT/Session 61 - 2006/FJI_61_2006.txt
TXT/Session 61 - 2006/TZA_61_2006.txt
TXT/Session 61 - 2006/UGA_61_2006.txt
TXT/Session 

TXT/Session 54 - 1999/ALB_54_1999.txt
TXT/Session 54 - 1999/BTN_54_1999.txt
TXT/Session 54 - 1999/NOR_54_1999.txt
TXT/Session 54 - 1999/TUN_54_1999.txt
TXT/Session 54 - 1999/EST_54_1999.txt
TXT/Session 54 - 1999/MDG_54_1999.txt
TXT/Session 54 - 1999/DZA_54_1999.txt
TXT/Session 54 - 1999/PRK_54_1999.txt
TXT/Session 54 - 1999/LKA_54_1999.txt
TXT/Session 54 - 1999/POL_54_1999.txt
TXT/Session 54 - 1999/PHL_54_1999.txt
TXT/Session 54 - 1999/GNB_54_1999.txt
TXT/Session 54 - 1999/BGR_54_1999.txt
TXT/Session 54 - 1999/GBR_54_1999.txt
TXT/Session 54 - 1999/BFA_54_1999.txt
TXT/Session 54 - 1999/PRT_54_1999.txt
TXT/Session 54 - 1999/CRI_54_1999.txt
TXT/Session 54 - 1999/ECU_54_1999.txt
TXT/Session 54 - 1999/CHN_54_1999.txt
TXT/Session 54 - 1999/BGD_54_1999.txt
TXT/Session 54 - 1999/MYS_54_1999.txt
TXT/Session 54 - 1999/BRN_54_1999.txt
TXT/Session 54 - 1999/SLB_54_1999.txt
TXT/Session 54 - 1999/TJK_54_1999.txt
TXT/Session 54 - 1999/ATG_54_1999.txt
TXT/Session 54 - 1999/AUT_54_1999.txt
TXT/Session 

TXT/Session 47 - 1992/NZL_47_1992.txt
TXT/Session 47 - 1992/PNG_47_1992.txt
TXT/Session 47 - 1992/NIC_47_1992.txt
TXT/Session 47 - 1992/TZA_47_1992.txt
TXT/Session 47 - 1992/FJI_47_1992.txt
TXT/Session 47 - 1992/BLZ_47_1992.txt
TXT/Session 47 - 1992/LSO_47_1992.txt
TXT/Session 47 - 1992/AGO_47_1992.txt
TXT/Session 47 - 1992/ITA_47_1992.txt
TXT/Session 47 - 1992/TCD_47_1992.txt
TXT/Session 47 - 1992/LVA_47_1992.txt
TXT/Session 47 - 1992/ARE_47_1992.txt
TXT/Session 47 - 1992/DMA_47_1992.txt
TXT/Session 47 - 1992/NGA_47_1992.txt
TXT/Session 47 - 1992/SEN_47_1992.txt
TXT/Session 47 - 1992/MLT_47_1992.txt
TXT/Session 47 - 1992/IRQ_47_1992.txt
TXT/Session 47 - 1992/JAM_47_1992.txt
TXT/Session 47 - 1992/YEM_47_1992.txt
TXT/Session 47 - 1992/KWT_47_1992.txt
TXT/Session 47 - 1992/BIH_47_1992.txt
TXT/Session 47 - 1992/IRN_47_1992.txt
TXT/Session 47 - 1992/NAM_47_1992.txt
TXT/Session 47 - 1992/STP_47_1992.txt
TXT/Session 47 - 1992/ROU_47_1992.txt
TXT/Session 47 - 1992/GRD_47_1992.txt
TXT/Session 

TXT/Session 69 - 2014/LIE_69_2014.txt
TXT/Session 69 - 2014/AZE_69_2014.txt
TXT/Session 69 - 2014/GRC_69_2014.txt
TXT/Session 69 - 2014/ISL_69_2014.txt
TXT/Session 69 - 2014/HUN_69_2014.txt


In [13]:
df_result.to_csv('un_speeches_uncategorised.csv')
print( f'{df_result.shape[0]} sentences containing the term \'sovereign\' ')

12952 sentences containing the term 'sovereign' 


Use the trained model to classify the sentences

In [14]:

x_new = vec.transform(df_result['text']).toarray()

# Predict Output
predictions = knn_model.predict(x_new)
df_result['category'] = predictions


In [15]:
print(df_result.columns)
df_result['year'] = df_result['year'].astype('int')
print(df_result.dtypes)

df_result.to_csv('un_speeches.csv')

Index(['file_name', 'country', 'year', 'text', 'orig_text', 'category'], dtype='object')
file_name    object
country      object
year          int64
text         object
orig_text    object
category     object
dtype: object


In [16]:
df_result['date'] = pd.to_datetime( df_result['year'] )

Make CSV files for each decade

In [17]:
import datetime
this_year = datetime.date.today().year


for year in range(1970,this_year,10):
    print(year)
    df_decade = df_result.query( 'date >= {} and date < {}'.format(year,year+10))
    outfile = f'speeches_{year}s.tsv'
    if df_decade.shape[0] > 0:
        df_decade.drop(columns=['date', 'text'])
        df_decade.to_csv(outfile) 


1970
1980
1990
2000
2010
2020
